export const CTA = {
    CHDE: {
        "shopNow": "Jetzt shoppen",
        "seeMore": "Mehr sehen",
        "watchNow": "Jetzt abspielen",
        "getCode": "Code erhalten",
        "getCodes": "Codes erhalten",
        "shopAllCategories" : "Stöbere in allen Kategorien",
        "chooseFrom": "Zur Auswahl stehen:",
        "interestedIn": "Das könnte dich auch interessieren",
        "shopLink": "https://www.beliani.ch/",
        "shopContent": "https://www.beliani.ch/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendChde.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/chdeending.jpg",
    },
    CHFR: {
        "shopNow": "Acheter maintenant",
        "seeMore": "En savoir plus",
        "watchNow": "Voir la vidéo",
        "getCode": "Obtenez le code",
        "getCodes": "Obtenez les codes",
        "shopAllCategories": "Achetez dans toutes les catégories",
        "chooseFrom": "Choisissez parmi:",
        "interestedIn": "Cela pourrait aussi vous intéresser",
        "shopLink": "https://www.beliani.ch/",
        "shopContent": "https://www.beliani.ch/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendChfr.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/chfrending.jpg",
    },
    DE: {
        "shopNow": "Jetzt shoppen",
        "seeMore": "Mehr sehen",
        "watchNow": "Jetzt abspielen",
        "getCode": "Code erhalten",
        "getCodes": "Codes erhalten",
        "shopAllCategories" : "Stöbere in allen Kategorien",
        "chooseFrom": "Zur Auswahl stehen:",
        "interestedIn": "Das könnte dich auch interessieren",
        "shopLink": "https://www.beliani.de/",
        "shopContent": "https://www.beliani.de/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendDe.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/deending.jpg",
    },
    UK: {
        "shopNow": "Shop now",
        "seeMore": "See More",
        "watchNow": "Watch Now",
        "getCode": "Get the code",
        "getCodes": "Get the codes",
        "shopAllCategories" : "Shop All Categories",
        "chooseFrom": "Choose from:",
        "interestedIn": "You May Be Also Interested In",
        "shopLink": "https://www.beliani.co.uk/",
        "shopContent": "https://www.beliani.co.uk/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendUk.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/ukending.jpg",
    },
    FR: {
        "shopNow": "Acheter maintenant",
        "seeMore": "En savoir plus",
        "watchNow": "Voir la vidéo",
        "getCode": "Obtenez le code",
        "getCodes": "Obtenez les codes",
        "shopAllCategories" : "Achetez dans toutes les catégories",
        "chooseFrom": "Choisissez parmi:",
        "interestedIn": "Cela pourrait aussi vous intéresser",
        "shopLink": "https://www.beliani.fr/",
        "shopContent": "https://www.beliani.fr/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendFr.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/frending.jpg",
    },
    AT: {
        "shopNow": "Jetzt shoppen",
        "seeMore": "Mehr sehen",
        "watchNow": "Jetzt abspielen",
        "getCode": "Code erhalten",
        "getCodes": "Codes erhalten",
        "shopAllCategories" : "Stöbere in allen Kategorien",
        "chooseFrom": "Zur Auswahl stehen:",
        "interestedIn": "Das könnte dich auch interessieren",
        "shopLink": "https://www.beliani.at/",
        "shopContent": "https://www.beliani.at/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendAt.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/atending.jpg",
    },
    ES: {
        "shopNow": "Compra ahora",
        "seeMore": "Ver más",
        "watchNow": "Ver Video",
        "getCode": "Obtener código",
        "getCodes": "Obtener códigos",
        "shopAllCategories" : "Ver todas las categorías",
        "chooseFrom": "Elige entre:",
        "interestedIn": "También te puede interesar",
        "shopLink": "https://www.beliani.es/",
        "shopContent": "https://www.beliani.es/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendEs.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/esending.jpg",
    },
    PL: {
        "shopNow": "Kup teraz",
        "seeMore": "Zobacz więcej",
        "watchNow": "Oglądaj",
        "getCode": "Odbierz kod",
        "getCodes": "Odbierz kody",
        "shopAllCategories" : "Zobacz wszystkie kategorie",
        "chooseFrom": "Wybierz spośród:",
        "interestedIn": "Może Cię także zainteresować",
        "shopLink": "https://www.beliani.pl/",
        "shopContent": "https://www.beliani.pl/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendPl.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/plending.jpg",
    },
    NL: {
        "shopNow": "Koop nu",
        "seeMore": "Bekijk meer",
        "watchNow": "Bekijk nu",
        "getCode": "Krijg code",
        "getCodes": "Krijg codes",
        "shopAllCategories" : "Shop alle categorieën",
        "chooseFrom": "Kies uit:",
        "interestedIn": "Misschien ben je ook geïnteresseerd in",
        "shopLink": "https://www.beliani.nl/",
        "shopContent": "https://www.beliani.nl/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendNl.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/nlending.jpg",
    },
    IT: {
        "shopNow": "Acquista ora",
        "seeMore": "Scopri di più",
        "watchNow": "Guarda Video",
        "getCode": "Ottieni Codice Sconto",
        "getCodes": "Ottieni Codici Sconto",
        "shopAllCategories" : "Scopri Tutto il Negozio",
        "chooseFrom": "Scegli tra:",
        "interestedIn": "Guarda anche",
        "shopLink": "https://www.beliani.it/",
        "shopContent": "https://www.beliani.it/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendIt.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/itending.jpg",
    },
    PT: {
        "shopNow": "Compre já",
        "seeMore": "Veja mais",
        "watchNow": "Veja agora",
        "getCode": "Veja o código",
        "getCodes": "Veja os códigos",
        "shopAllCategories" : "Veja todas as categorias",
        "chooseFrom": "Escolha entre:",
        "interestedIn": "Também pode ter interesse em",
        "shopLink": "https://www.beliani.pt/",
        "shopContent": "https://www.beliani.pt/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendPt.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/ptending.jpg",
    },
    SE: {
        "shopNow": "Handla nu",
        "seeMore": "Se mer",
        "watchNow": "Titta nu",
        "getCode": "Hämta kod",
        "getCodes": "Hämta koder",
        "shopAllCategories" : "Handla alla kategorier",
        "chooseFrom": "Välj mellan:",
        "interestedIn": "Du kanske också är intresserad av",
        "shopLink": "https://www.beliani.se/",
        "shopContent": "https://www.beliani.se/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendSe.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/seending.jpg",
    },
    HU: {
        "shopNow": "Fedezd fel",
        "seeMore": "Tekintsd meg",
        "watchNow": "Nézd meg",
        "getCode": "Kattints a kódért",
        "getCodes": "Kattints a kódokért",
        "shopAllCategories" : "Fedezd fel az összes kategóriát",
        "chooseFrom": "Válassz:",
        "interestedIn": "Ez is érdekelhet",
        "shopLink": "https://www.beliani.hu/",
        "shopContent": "https://www.beliani.hu/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendHu.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/huending.jpg",
    },
    DK: {
        "shopNow": "Køb nu",
        "seeMore": "Se mere",
        "watchNow": "Se nu",
        "getCode": "Få koden",
        "getCodes": "Få koderne",
        "shopAllCategories" : "Gennemse alle kategorierne",
        "chooseFrom": "Vælg mellem:",
        "interestedIn": "Se også",
        "shopLink": "https://www.beliani.dk/",
        "shopContent": "https://www.beliani.dk/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendDk.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/dkending.jpg",
    },
    CZ: {
        "shopNow": "Do obchodu",
        "seeMore": "Zobraziť viac",
        "watchNow": "Přehrát nyní",
        "getCode": "Získat kód",
        "getCodes": "Získat kódy",
        "shopAllCategories" : "Objevte všechny kategorie",
        "chooseFrom": "Vyberte si z:",
        "interestedIn": "Mohlo by vás také zajímat",
        "shopLink": "https://www.beliani.cz/",
        "shopContent": "https://www.beliani.cz/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendCz.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/czending.jpg",
    },
    FI: {
        "shopNow": "Osta nyt",
        "seeMore": "Katso lisää",
        "watchNow": "Katso nyt",
        "getCode": "Hanki koodi",
        "getCodes": "Hanki koodit",
        "shopAllCategories" : "Katso kaikki kategoriat",
        "chooseFrom": "Valitse näistä:",
        "interestedIn": "Saatat pitää myös näistä",
        "shopLink": "https://www.beliani.fi/",
        "shopContent": "https://www.beliani.fi/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendFi.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/fiending.jpg",
    },
    NO: {
        "shopNow": "Kjøp nå",
        "seeMore": "Se mer",
        "watchNow": "Se nå",
        "getCode": "Få kode",
        "getCodes": "Få koder",
        "shopAllCategories" : "Bla gjennom alle kategorier",
        "chooseFrom": "Velg mellom:",
        "interestedIn": "Du kan også være interessert i",
        "shopLink": "https://www.beliani.no/",
        "shopContent": "https://www.beliani.no/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendNo.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/noending.jpg",
    },
    SK: {
        "shopNow": "Do obchodu",
        "seeMore": "Zobraziť viac",
        "watchNow": "Pozrieť video",
        "getCode": "Získať kód",
        "getCodes": "Získať kódy",
        "shopAllCategories" : "Objavte všetky kategórie",
        "chooseFrom": "Vyberte si z:",
        "interestedIn": "Mohlo by vás zaujímať",
        "shopLink": "https://www.beliani.sk/",
        "shopContent": "https://www.beliani.sk/content/",
        "soonEnding": "https://beliani.info/newsletter/2022/soonendSk.jpg",
        "soonEndingWithoutPadding": "https://beliani.info/newsletter/2022/skending.jpg",
    },
}

const currencies = {
    euro: "€",
    swissFranc: "Fr.",
    poundSterling: "£",
    hungarianForint: "Ft",
    swedishKrona: "kr",
    danishKrona: "kr.",
    czechKrona: "Kč",
    norwegianKrone: ",-"
}
const relativePriceFormat = {
    DE: {
        currency: currencies.euro,
    },
    CHDE: {
        currency: currencies.swissFranc,
    },
    AT: {
        currency: currencies.euro,
    },
    FR: {
        currency: currencies.euro,
    },
    CHFR: {
        currency: currencies.swissFranc,
    },
    IT: {
        currency: currencies.euro,
    },
    UK: {
        currency: currencies.poundSterling,
    },
    ES: {
        currency: currencies.euro,
    },
    PT: {
        currency: currencies.euro,
    },
    PL: {
        currency: "",
    },
    HU: {
        currency: currencies.hungarianForint,
    },
    NL: {
        currency: currencies.euro,
    },
    SE: {
        currency: currencies.swedishKrona,
    },
    DK: {
        currency: currencies.danishKrona,
    },
    CZ: {
        currency: currencies.czechKrona,
    },
    FI: {
        currency: currencies.euro,
    },
    NO: {
        currency: currencies.norwegianKrone,
    },
    SK: {
        currency: currencies.euro,
    },
}
const priceFormats = {
    DE: " " + relativePriceFormat.DE.currency,
    CHDE: " " + relativePriceFormat.CHDE.currency,
    AT: " " + relativePriceFormat.AT.currency,
    FR: " " + relativePriceFormat.FR.currency,
    CHFR: " " + relativePriceFormat.CHFR.currency,
    IT: " " + relativePriceFormat.IT.currency,
    UK: relativePriceFormat.UK.currency,
    ES: " " + relativePriceFormat.ES.currency,
    PT: " " + relativePriceFormat.PT.currency,
    PL: relativePriceFormat.PL.currency,
    HU: " " + relativePriceFormat.HU.currency,
    NL: relativePriceFormat.NL.currency + " ",
    SE: " " + relativePriceFormat.SE.currency,
    DK: " " + relativePriceFormat.DK.currency,
    CZ: " " + relativePriceFormat.CZ.currency,
    FI: " " + relativePriceFormat.FI.currency,
    NO: relativePriceFormat.NO.currency,
    SK: " " + relativePriceFormat.SK.currency
}

const relativeCategories = {
    sofas: {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2298&shop_id=1",
      categories: {
        "CZ": "pohovky",
        "DK": "sofaer",
        "NL": "banken",
        "UK": "sofas",
        "FI": "sohvat",
        "FR": "canapes",
        "DE": "sofas",
        "AT": "sofas",
        "CHDE": "sofas",
        "CHFR": "canapes",
        "HU": "kanapek",
        "IT": "divani",
        "NO": "sofaer",
        "PL": "sofy",
        "PT": "sofas",
        "SK": "pohovky",
        "ES": "sofas",
        "SE": "soffor"
      }
    },
    beds: {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2525&shop_id=1",
      categories: {
        "CZ": "postele",
        "DK": "senge",
        "NL": "bedden",
        "UK": "beds",
        "FI": "sangyt",
        "FR": "lits",
        "DE": "betten",
        "AT": "betten",
        "CHDE": "betten",
        "CHFR": "lits",
        "HU": "agyak",
        "IT": "letti",
        "NO": "senger",
        "PL": "lozka",
        "PT": "camas",
        "SK": "postele",
        "ES": "camas",
        "SE": "sangar"
      } 
    },
    chairs: {
      link: "",
      categories: {
        "CZ": "zidle-a-kresla",
        "DK": "stole",
        "NL": "stoelen",
        "UK": "chairs",
        "FI": "tuolit",
        "FR": "chaises",
        "DE": "stuehle",
        "AT": "stuehle",
        "CHDE": "stuehle",
        "CHFR": "chaises",
        "HU": "szekek",
        "IT": "sedie",
        "NO": "stoler",
        "PL": "krzesla",
        "PT": "cadeiras",
        "SK": "stolicky-a-kresla",
        "ES": "sillas",
        "SE": "stolar"
      }
    },
    textiles: {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=3319&shop_id=1",
      categories: {
        "CZ": "textil",
        "DK": "tekstiler",
        "NL": "textiel",
        "UK": "textiles",
        "FI": "tekstiilit",
        "FR": "textiles",
        "DE": "textilien",
        "AT": "textilien",
        "CHDE": "textilien",
        "CHFR": "textiles",
        "HU": "textiliak",
        "IT": "tessili",
        "NO": "tekstiler",
        "PL": "tekstylia",
        "PT": "texteis",
        "SK": "textil",
        "ES": "textiles",
        "SE": "textilier"
      }
    },
    "outdoor-furniture": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2410&shop_id=1",
      categories: {
        "CZ": "venkovni-nabytek",
        "DK": "havemoebler",
        "NL": "tuinmeubels",
        "UK": "outdoor-furniture",
        "FI": "ulkokalusteet",
        "FR": "mobilier-de-jardin",
        "DE": "gartenmobel",
        "AT": "gartenmobel",
        "CHDE": "gartenmobel",
        "CHFR": "mobilier-de-jardin",
        "HU": "kulter",
        "IT": "arredo-giardino",
        "NO": "hagemobler",
        "PL": "meble-ogrodowe",
        "PT": "mobiliario-de-jardim",
        "SK": "zahradny-nabytok",
        "ES": "muebles-de-exterior",
        "SE": "utemobler"
      }
    },
    mattresses: {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2495&shop_id=1",
      categories: {
        "CZ": "matrace",
        "DK": "madrasser",
        "NL": "matrassen",
        "UK": "mattresses",
        "FI": "patja",
        "FR": "matelas",
        "DE": "matratzen",
        "AT": "matratzen",
        "CHDE": "matratzen",
        "CHFR": "matelas",
        "HU": "matracok",
        "IT": "materassi",
        "NO": "madrasser",
        "PL": "materace",
        "PT": "colchao",
        "SK": "matrace",
        "ES": "colchones",
        "SE": "madrasser"
      }
    },
    tables: {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=1695&shop_id=1",
      categories: {
        "CZ": "stoly",
        "DK": "borde",
        "NL": "tafels",
        "UK": "tables",
        "FI": "poydat",
        "FR": "tables",
        "DE": "tische",
        "AT": "tische",
        "CHDE": "tische",
        "CHFR": "tables",
        "HU": "asztalok",
        "IT": "tavoli",
        "NO": "bord",
        "PL": "stoly",
        "PT": "mesas",
        "SK": "stoly",
        "ES": "mesas",
        "SE": "bord"
      }
    },
    armchairs: {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2321&shop_id=1",
      categories: {
        "CZ": "kresla",
        "DK": "lenestole",
        "NL": "fauteuils",
        "UK": "armchairs",
        "FI": "nojatuolit",
        "FR": "fauteuils",
        "DE": "sessel",
        "AT": "sessel",
        "CHDE": "sessel",
        "CHFR": "fauteuils",
        "HU": "fotelek",
        "IT": "poltrone",
        "NO": "lenestoler",
        "PL": "fotele",
        "PT": "poltrona",
        "SK": "kresla",
        "ES": "sillones",
        "SE": "fatolj"
      }
    },
    storage: {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2722&shop_id=1",
      categories: {
        "CZ": "ulozny-prostor",
        "DK": "opbevaring",
        "NL": "opbergen",
        "UK": "storage",
        "FI": "sailytys",
        "FR": "espace-rangement",
        "DE": "aufbewahrung",
        "AT": "aufbewahrung",
        "CHDE": "aufbewahrung",
        "CHFR": "espace-rangement",
        "HU": "tarolo-szekrenyek",
        "IT": "mobili-portaoggetti",
        "NO": "oppbevaring",
        "PL": "przechowywanie",
        "PT": "arrumacao",
        "SK": "ulozny-priestor",
        "ES": "organizacion-y-almacenaje",
        "SE": "forvaring"
      }
    },
    "tv-stands": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2725&shop_id=1",
      categories: {
        "CZ": "tv-stolky",
        "DK": "tv-borde",
        "NL": "tv-meubels",
        "UK": "tv-stands",
        "FI": "tv-tasot",
        "FR": "meubles-tv",
        "DE": "tv-moebel",
        "AT": "tv-moebel",
        "CHDE": "tv-moebel",
        "CHFR": "meubles-tv",
        "HU": "tv-allvanyok",
        "IT": "mobili-tv",
        "NO": "tv-benker",
        "PL": "szafki-rtv",
        "PT": "moveis-de-tv",
        "SK": "televizne-stoliky",
        "ES": "muebles-tv",
        "SE": "tv-bankar"
      }
    },
    lighting: {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=1707&shop_id=1",
      categories: {
        "CZ": "svitidla",
        "DK": "belysning",
        "NL": "lampen",
        "UK": "lighting",
        "FI": "valaisimet",
        "FR": "lampes",
        "DE": "lampen",
        "AT": "lampen",
        "CHDE": "lampen",
        "CHFR": "lampes",
        "HU": "lampak",
        "IT": "illuminazione",
        "NO": "belysning",
        "PL": "oswietlenie",
        "PT": "candeeiros",
        "SK": "svietidla",
        "ES": "lamparas",
        "SE": "lampor"
      }
    },
    rugs: {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=1870&shop_id=1",
      categories: {
        "CZ": "koberce",
        "DK": "gulvtepper",
        "NL": "vloerkleden",
        "UK": "rugs",
        "FI": "matot",
        "FR": "tapis",
        "DE": "teppich",
        "AT": "teppich",
        "CHDE": "teppich",
        "CHFR": "tapis",
        "HU": "szonyegek",
        "IT": "tappeti",
        "NO": "tepper",
        "PL": "dywany",
        "PT": "tapetes",
        "SK": "koberce",
        "ES": "alfombras",
        "SE": "mattor"
      }
    },
    "children-room": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=3171&shop_id=1",
      categories: {
        "CZ": "detsky-pokoj",
        "DK": "bornevaerelse",
        "NL": "kinderkamer",
        "UK": "children-room",
        "FI": "lastenhuone",
        "FR": "chambre-enfant",
        "DE": "kindermoebel",
        "AT": "kindermoebel",
        "CHDE": "kindermoebel",
        "CHFR": "chambre-enfant",
        "HU": "gyerekszoba-butorok",
        "IT": "arredi-per-bambini",
        "NO": "barnerom",
        "PL": "pokoj-dzieciecy",
        "PT": "quarto-de-crianca",
        "SK": "detska-izba",
        "ES": "cuarto-de-los-ninos",
        "SE": "barnrum"
      }
    },
    "bathtubs-hot-tubs": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2451&shop_id=1",
      categories: {
        "CZ": "vany-a-virivky",
        "DK": "badekar-og-spabad",
        "NL": "baden",
        "UK": "bathtubs-hot-tubs",
        "FI": "kylpyammeet-ja-poreammeet",
        "FR": "baignoires",
        "DE": "badewanne-and-whirlpools",
        "AT": "badewanne-and-whirlpools",
        "CHDE": "badewanne-and-whirlpools",
        "CHFR": "baignoires",
        "HU": "kadak-es-pezsgofurdok",
        "IT": "vasche",
        "NO": "bad-og-boblebad",
        "PL": "wanny-i-wanny-z-hydromasazem",
        "PT": "banheiras-de-hidromassagem",
        "SK": "vane-a-virivky",
        "ES": "baneras-y-jacuzzis",
        "SE": "badkar"
      }
    },
    "living-room-furniture": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2273&shop_id=1",
      categories: {
        "CZ": "nabytek-do-obyvaku",
        "DK": "stuemobler",
        "NL": "woonkamer",
        "UK": "living-room-furniture",
        "FI": "olohuoneen-kalusteet",
        "FR": "meubles-de-salon",
        "DE": "wohnzimmer-moebel",
        "AT": "wohnzimmer-moebel",
        "CHDE": "wohnzimmer-moebel",
        "CHFR": "meubles-de-salon",
        "HU": "nappali-butorok",
        "IT": "soggiorno",
        "NO": "stuemoebler",
        "PL": "meble-do-salonu",
        "PT": "sala",
        "SK": "nabytok-do-obyvacky",
        "ES": "salon",
        "SE": "vardagsrumsmobler"
      }
    },
    "bedroom-furniture": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2274&shop_id=1",
      categories: {
        "CZ": "nabytek-do-loznice",
        "DK": "soveverelsesmobler",
        "NL": "slaapkamer",
        "UK": "bedroom-furniture",
        "FI": "makuuhuoneen-kalusteet",
        "FR": "meubles-de-chambre",
        "DE": "schlafzimmer-moebel",
        "AT": "schlafzimmer-moebel",
        "CHDE": "schlafzimmer-moebel",
        "CHFR": "meubles-de-chambre",
        "HU": "haloszoba-butorok",
        "IT": "camera-da-letto",
        "NO": "soveromsmoebler",
        "PL": "meble-do-sypialni",
        "PT": "quarto",
        "SK": "nabytok-do-spalne",
        "ES": "dormitorio",
        "SE": "sovrumsmobler"
      }
    },
    "dining-room-furniture": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2312&shop_id=1",
      categories: {
        "CZ": "nabytek-do-jidelny",
        "DK": "spisestuemobler",
        "NL": "eetkamer",
        "UK": "dining-room-furniture",
        "FI": "ruokailutila",
        "FR": "meubles-de-salle-a-manger",
        "DE": "esszimmer-moebel",
        "AT": "esszimmer-moebel",
        "CHDE": "esszimmer-moebel",
        "CHFR": "meubles-de-salle-a-manger",
        "HU": "etkezo-butorok",
        "IT": "sala-da-pranzo",
        "NO": "spisestuemobler",
        "PL": "meble-do-jadalni",
        "PT": "sala-de-jantar",
        "SK": "nabytok-do-jedalne",
        "ES": "comedor",
        "SE": "matsalsmobler"
      }
    },
    "bathroom-furniture": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2314&shop_id=1",
      categories: {
        "CZ": "nabytek-do-koupelny",
        "DK": "badeverelsesmobler",
        "NL": "badkamer",
        "UK": "bathroom-furniture",
        "FI": "kylpyhuoneen-kalusteet",
        "FR": "salle-de-bain",
        "DE": "badmoebel",
        "AT": "badmoebel",
        "CHDE": "badezimmer-moebel",
        "CHFR": "salle-de-bain",
        "HU": "furdoszoba-butorok",
        "IT": "bagno",
        "NO": "baderomsmoebler",
        "PL": "meble-lazienkowe",
        "PT": "casa-de-banho",
        "SK": "nabytok-do-kupelne",
        "ES": "cuarto-de-bano",
        "SE": "badrumsmobler"
      }
    },
    "garden-furniture": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2315&shop_id=1",
      categories: {
        "CZ": "zahradni-nabytek",
        "DK": "havemobler",
        "NL": "tuinmeubelen",
        "UK": "garden-furniture",
        "FI": "puutarhakalusteet",
        "FR": "meubles-de-jardin",
        "DE": "gartenmoebel",
        "AT": "gartenmoebel",
        "CHDE": "gartenmoebel",
        "CHFR": "meubles-de-jardin",
        "HU": "kerti-garniturak",
        "IT": "giardino",
        "NO": "hagemoebler",
        "PL": "ogrod",
        "PT": "exterior",
        "SK": "zahrada",
        "ES": "jardin",
        "SE": "tradgardsmobler"
      }
    },
    office: {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2313&shop_id=1",
      categories: {
        "CZ": "nabytek-do-kancelare",
        "DK": "kontormobler",
        "NL": "werkkamer",
        "UK": "office-furniture",
        "FI": "toimistokalusteet",
        "FR": "mobilier-de-bureau",
        "DE": "bueromoebel",
        "AT": "bueromoebel",
        "CHDE": "bueromoebel",
        "CHFR": "mobilier-de-bureau",
        "HU": "irodabutorok",
        "IT": "ufficio",
        "NO": "kontormobler",
        "PL": "meble-biurowe",
        "PT": "escritorio",
        "SK": "nabytok-do-kancelarie",
        "ES": "oficina",
        "SE": "kontorsmobler"
      }
    },
    hallway: {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=3379&shop_id=1",
      categories: {
        "CZ": "predsin",
        "DK": "entre",
        "NL": "hal",
        "UK": "hallway",
        "FI": "eteinen",
        "FR": "hall-d-entree",
        "DE": "flurmoebel",
        "AT": "flurmoebel",
        "CHDE": "flurmoebel",
        "CHFR": "hall-d-entree",
        "HU": "eloszoba-butorok",
        "IT": "ingresso-it",
        "NO": "gang",
        "PL": "meble-do-przedpokoju",
        "PT": "entrada-pt",
        "SK": "predsien",
        "ES": "entrada-es",
        "SE": "hall"
      }
    },
    sideboards: {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2736&shop_id=1",
      categories: {
        "CZ": "nizke-skrinky",
        "DK": "skaenke",
        "NL": "sideboards",
        "UK": "sideboards",
        "FI": "senkit",
        "FR": "commodes",
        "DE": "sideboard",
        "AT": "sideboard",
        "CHDE": "sideboard",
        "CHFR": "commodes",
        "HU": "polcos-szekrenyek-es-talalok",
        "IT": "credenze",
        "NO": "skjenker",
        "PL": "szafki",
        "PT": "aparadores",
        "SK": "nizke-skrinky",
        "ES": "aparadores",
        "SE": "skap-och-skankar"
      }
    },
    "home-accessories": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2560&shop_id=1",
      categories: {
        "CZ": "doplnky",
        "DK": "boligtilbehor",
        "NL": "woonaccessoires",
        "UK": "home-accessories",
        "FI": "sisustustuotteet",
        "FR": "accessoires",
        "DE": "wohnzubehor",
        "AT": "wohnzubehor",
        "CHDE": "wohnzubehor",
        "CHFR": "accessoires",
        "HU": "otthoni-kiegeszitok",
        "IT": "accessori-casa",
        "NO": "hjemtilbehoer",
        "PL": "dodatki",
        "PT": "acessorios",
        "SK": "doplnky",
        "ES": "accesorios-del-hogar",
        "SE": "tillbehor"
      }
    },
    mirrors: {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=3153&shop_id=1",
      categories: {
        "CZ": "zrcadla",
        "DK": "spejle",
        "NL": "spiegels",
        "UK": "mirrors",
        "FI": "peilit",
        "FR": "miroirs",
        "DE": "spiegel-ch",
        "AT": "spiegel-ch",
        "CHDE": "spiegel-de",
        "CHFR": "miroirs",
        "HU": "tukor",
        "IT": "specchi",
        "NO": "speil",
        "PL": "lustra",
        "PT": "espelhos",
        "SK": "zrkadla",
        "ES": "espejos",
        "SE": "speglar"
      }
    },
    "accessories-decor": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2320&shop_id=1",
      categories: {
        "CZ": "bytove-doplnky",
        "DK": "boligtilbehoer",
        "NL": "woonaccessoires-decoratie",
        "UK": "accessories-decor",
        "FI": "sisustustarvikkeet",
        "FR": "accessoires-maison",
        "DE": "wohnaccessoires",
        "AT": "wohnaccessoires",
        "CHDE": "wohnaccessoires",
        "CHFR": "accessoires-maison",
        "HU": "kiegeszitok",
        "IT": "accessori-decor",
        "NO": "tilbehoer",
        "PL": "akcesoria",
        "PT": "acessorios-para-casa",
        "SK": "bytove-doplnky",
        "ES": "accesorios",
        "SE": "hemtillbehor"
      }
    },
    stools: {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2386&shop_id=1",
      categories: {
        "CZ": "stolicky-a-taburety",
        "DK": "diverse-stole",
        "NL": "krukken",
        "UK": "stools",
        "FI": "jakkarat",
        "FR": "tabourets-et-poufs",
        "DE": "hocker",
        "AT": "hocker",
        "CHDE": "hocker",
        "CHFR": "tabourets-et-poufs",
        "HU": "uloalkalmatossagok",
        "IT": "sgabelli",
        "NO": "diverse-stoler",
        "PL": "pufy-i-stolki",
        "PT": "bancos-e-tamboretes",
        "SK": "stolicky-a-taburety",
        "ES": "taburetes",
        "SE": "puffar-och-pallar"
      }
    },
    "bed-accessories": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2484&shop_id=1",
      categories: {
        "CZ": "prislusenstvi-k-postelim",
        "DK": "tilbehor-til-senge",
        "NL": "bedaccessoires",
        "UK": "bed-accessories",
        "FI": "sankytarvikkeet",
        "FR": "accessoires-de-literie",
        "DE": "bett-zubehor",
        "AT": "bett-zubehor",
        "CHDE": "bett-zubehor",
        "CHFR": "accessoires-de-literie",
        "HU": "agy-kiegeszitok",
        "IT": "accessori-letti",
        "NO": "sengetilbehoer",
        "PL": "akcesoria-do-lozek",
        "PT": "acessorios-para-camas",
        "SK": "prislusenstvo-k-posteliam",
        "ES": "accesorios-para-camas",
        "SE": "sangtillbehor"
      }
    },
    showers: {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=3093&shop_id=1",
      categories: {
        "CZ": "sprchy",
        "DK": "brusebade",
        "NL": "douches",
        "UK": "showers",
        "FI": "suihkutarvikkeet",
        "FR": "douches",
        "DE": "duschen",
        "AT": "duschen",
        "CHDE": "duschen",
        "CHFR": "douches",
        "HU": "zuhanyzok",
        "IT": "docce",
        "NO": "dusjer",
        "PL": "prysznice",
        "PT": "chuveiros",
        "SK": "sprchy",
        "ES": "duchas",
        "SE": "duschar"
      }
    },
    "bathroom-fittings": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2519&shop_id=1",
      categories: {
        "CZ": "vodovodni-baterie",
        "DK": "armaturer",
        "NL": "kranen",
        "UK": "bathroom-fittings",
        "FI": "kylpyhuoneen-hanat",
        "FR": "robinetterie",
        "DE": "armaturen",
        "AT": "armaturen",
        "CHDE": "armaturen",
        "CHFR": "robinetterie",
        "HU": "furdoszoba-csaptelepek",
        "IT": "rubinetteria",
        "NO": "armaturer",
        "PL": "baterie-lazienkowe",
        "PT": "torneiras-e-chuveiros",
        "SK": "kupelnove-baterie",
        "ES": "griferia",
        "SE": "blandare"
      }
    },
    "wooden-beds": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2544&shop_id=1",
      categories: {
        "CZ": "drevene-postele",
        "DK": "traesenge",
        "NL": "houten-bedden",
        "UK": "wooden-beds",
        "FI": "puiset-sangyt",
        "FR": "lits-en-bois",
        "DE": "holzbetten",
        "AT": "holzbetten",
        "CHDE": "holzbett",
        "CHFR": "lits-en-bois",
        "HU": "fa-agyak",
        "IT": "letti-in-legno",
        "NO": "tresenger",
        "PL": "lozka-drewniane",
        "PT": "camas-de-madeira",
        "SK": "drevene-postele",
        "ES": "camas-de-madera",
        "SE": "trasangar"
      }
    },
    "storage-beds": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2606&shop_id=1",
      categories: {
        "CZ": "postel-s-uloznym-prostorem",
        "DK": "senge-med-opbevaring",
        "NL": "bedden-met-opbergruimte",
        "UK": "storage-beds",
        "FI": "sailytystilalliset-sangyt",
        "FR": "lits-avec-coffre",
        "DE": "mit-bettkasten",
        "AT": "mit-bettkasten",
        "CHDE": "mit-bettkasten",
        "CHFR": "lits-avec-coffre",
        "HU": "agyak-taroloval",
        "IT": "letti-contenitore",
        "NO": "senger-med-oppbevaring",
        "PL": "ze-skrzynia",
        "PT": "camas-com-arrumacao",
        "SK": "postel-s-uloznym-priestorom",
        "ES": "camas-con-almacenaje",
        "SE": "sangar-med-forvaring"
      }
    },
    "low-beds": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2540&shop_id=1",
      categories: {
        "CZ": "postele-na-platforme",
        "DK": "futon-senge",
        "NL": "futonbedden",
        "UK": "low-beds",
        "FI": "matalat-sangyt",
        "FR": "lits-style-japonais",
        "DE": "futonbetten",
        "AT": "futonbetten",
        "CHDE": "futonbetten",
        "CHFR": "lits-style-japonais",
        "HU": "futonagyak",
        "IT": "letti-futon",
        "NO": "plattformsenger",
        "PL": "lozka-niskie",
        "PT": "futons",
        "SK": "postele-na-platforme",
        "ES": "camas-de-plataforma",
        "SE": "futon-sangar"
      }
    },
    "divan-beds": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2539&shop_id=1",
        categories: {
        "CZ": "kontinentalni-postele",
        "DK": "kontinentalsenge",
        "NL": "boxsprings",
        "UK": "divan-beds",
        "FI": "jenkkisangyt",
        "FR": "lits-boxspring",
        "DE": "boxspringbetten",
        "AT": "boxspringbetten",
        "CHDE": "boxspringbett",
        "CHFR": "lits-boxspring",
        "HU": "boxspring-agyak",
        "IT": "letti-boxspring",
        "NO": "kontinentalsenger",
        "PL": "lozka-kontynentalne",
        "PT": "camas-continentais",
        "SK": "kontinentalne-postele",
        "ES": "camas-continentales",
        "SE": "kontinentalsangar"
      }
    },
    "round-beds": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2534&shop_id=1",
        categories: {
          "CZ": "kulate-postele",
          "DK": "runde-senge",
          "NL": "ronde-bedden",
          "UK": "round-beds",
          "FI": "pyoreat-sangyt",
          "FR": "lits-ronds",
          "DE": "rundbetten",
          "AT": "rundbetten",
          "CHDE": "rundbetten",
          "CHFR": "lits-ronds",
          "HU": "kor-alaku-agyak",
          "IT": "letti-tondi",
          "NO": "runde-senger",
          "PL": "lozka-okragle",
          "PT": "camas-redondas",
          "SK": "okruhle-postele",
          "ES": "camas-redondas",
          "SE": "runda-sangar"
      }
    },
    "waterbeds": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2549&shop_id=1",
      categories: {
        "CZ": "vodni-postele",
        "DK": "vandsenge",
        "NL": "waterbedden",
        "UK": "waterbeds",
        "FI": "vesisangyt",
        "FR": "lits-a-eau",
        "DE": "wasserbetten",
        "AT": "wasserbetten",
        "CHDE": "wasserbett",
        "CHFR": "lits-a-eau",
        "HU": "vizagyak",
        "IT": "letti-ad-acqua",
        "NO": "vannsenger",
        "PL": "lozka-wodne",
        "PT": "cama-de-agua",
        "SK": "vodne-postele",
        "ES": "camas-de-agua",
        "SE": "vattensang"
      }
    },
    "bunk-beds": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2552&shop_id=1",
      categories: {
        "CZ": "palandy",
        "DK": "kojesenge",
        "NL": "hoogslapers",
        "UK": "bunk-beds",
        "FI": "kerrossangyt",
        "FR": "lits-superposes",
        "DE": "hochbetten",
        "AT": "hochbetten",
        "CHDE": "hochbetten",
        "CHFR": "lits-superposes",
        "HU": "emeletes-agyak",
        "IT": "letti-a-castello",
        "NO": "koeyesenger",
        "PL": "lozka-pietrowe",
        "PT": "beliches",
        "SK": "poschodove-postele",
        "ES": "literas",
        "SE": "vaningssangar"
      }
    },
    "trundle-beds": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2769&shop_id=1",
      categories: {
        "CZ": "postele-s-pristylkou",
        "DK": "dagsenge",
        "NL": "onderschuifbed",
        "UK": "trundle-beds",
        "FI": "levitettavat-sangyt",
        "FR": "lits-gigognes",
        "DE": "tagesbetten",
        "AT": "tagesbetten",
        "CHDE": "tagesbetten",
        "CHFR": "lits-gigognes",
        "HU": "heverok",
        "IT": "letti-da-giorno",
        "NO": "dagsenger",
        "PL": "lozka-wysuwane",
        "PT": "camas-duplas-em-gaveta",
        "SK": "postele-s-pristelkou",
        "ES": "camas-nido",
        "SE": "dagbaddar"
      }
    },
    "adjustable-beds": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2816&shop_id=1",
      categories: {
        "CZ": "nastavitelne-postele",
        "DK": "elevationssenge",
        "NL": "verstelbare-bedden",
        "UK": "adjustable-beds",
        "FI": "saatosangyt",
        "FR": "lits-de-relaxation",
        "DE": "verstellbare-betten",
        "AT": "verstellbare-betten",
        "CHDE": "verstellbare-betten",
        "CHFR": "lits-de-relaxation",
        "HU": "allithato-agyak",
        "IT": "letti-regolabili",
        "NO": "justerbare-senger",
        "PL": "lozka-regulowane",
        "PT": "camas-ajustaveis",
        "SK": "polohovatelne-postele",
        "ES": "camas-ajustables",
        "SE": "stallbara-sangar"
      }
    },
    "fabric-beds": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2543&shop_id=1",
      categories: {
        "CZ": "calounene-postele",
        "DK": "polstrede-senge",
        "NL": "gestoffeerde-bedden",
        "UK": "fabric-beds",
        "FI": "kangassangyt",
        "FR": "lits-en-tissu",
        "DE": "polsterbetten",
        "AT": "polsterbetten",
        "CHDE": "polsterbett",
        "CHFR": "lits-en-tissu",
        "HU": "karpitozott-agyak",
        "IT": "letti-in-tessuto",
        "NO": "polstrede-senger",
        "PL": "lozka-tapicerowane",
        "PT": "camas-estofadas",
        "SK": "calunene-postele",
        "ES": "camas-tapizadas",
        "SE": "stoppade-sangar"
      }
    },
    "velvet-beds": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2927&shop_id=1",
      categories: {
        "CZ": "sametove-postele",
        "DK": "velour-senge",
        "NL": "velvet-bedden",
        "UK": "velvet-beds",
        "FI": "samettisangyt",
        "FR": "lits-en-velours",
        "DE": "samtbetten",
        "AT": "samtbetten",
        "CHDE": "samtbetten",
        "CHFR": "lits-en-velours",
        "HU": "barsony-agyak",
        "IT": "letti-in-velluto",
        "NO": "floyelssenger",
        "PL": "lozka-welurowe",
        "PT": "camas-de-veludo",
        "SK": "zamatove-postele",
        "ES": "camas-de-terciopelo",
        "SE": "sammetssangar"
      }
    },
    "wooden-beds": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2544&shop_id=1",
      categories: {
        "CZ": "drevene-postele",
        "DK": "traesenge",
        "NL": "houten-bedden",
        "UK": "wooden-beds",
        "FI": "puiset-sangyt",
        "FR": "lits-en-bois",
        "DE": "holzbetten",
        "AT": "holzbetten",
        "CHDE": "holzbett",
        "CHFR": "lits-en-bois",
        "HU": "fa-agyak",
        "IT": "letti-in-legno",
        "NO": "tresenger",
        "PL": "lozka-drewniane",
        "PT": "camas-de-madeira",
        "SK": "drevene-postele",
        "ES": "camas-de-madera",
        "SE": "trasangar"
      }
    },
    "metal-beds": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2545&shop_id=1",
      categories: {
        "CZ": "kovove-postele",
        "DK": "metalsenge",
        "NL": "metalen-bedden",
        "UK": "metal-beds",
        "FI": "metallisangyt",
        "FR": "lits-en-metal",
        "DE": "metallbetten",
        "AT": "metallbetten",
        "CHDE": "metallbetten",
        "CHFR": "lits-en-metal",
        "HU": "fem-agyak",
        "IT": "letti-in-metallo",
        "NO": "metallsenger",
        "PL": "lozka-metalowe",
        "PT": "camas-de-metal",
        "SK": "kovove-postele",
        "ES": "camas-de-metal",
        "SE": "metallsangar"
      }
    },
    "leather-beds": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2542&shop_id=1",
      categories: {
        "CZ": "kozene-postele",
        "DK": "laeder-senge",
        "NL": "leren-bedden",
        "UK": "leather-beds",
        "FI": "nahkasangyt",
        "FR": "lits-en-cuir",
        "DE": "lederbetten",
        "AT": "lederbetten",
        "CHDE": "lederbett",
        "CHFR": "lits-en-cuir",
        "HU": "bor-agyak",
        "IT": "letti-in-pelle",
        "NO": "skinnsenger",
        "PL": "lozka-skorzane",
        "PT": "camas-em-pele",
        "SK": "kozene-postele",
        "ES": "camas-de-piel",
        "SE": "skinnsangar"
      }
    },
    "bedroom-set": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2992&shop_id=1",
      categories: {
        "CZ": "sady-do-loznice",
        "DK": "sovevaerelses-saet",
        "NL": "slaapkamersets",
        "UK": "bedroom-set",
        "FI": "makuuhuonesetit",
        "FR": "ensembles-de-chambre-a-coucher",
        "DE": "schlafzimmersets",
        "AT": "schlafzimmersets",
        "CHDE": "schlafzimmersets",
        "CHFR": "ensembles-de-chambre-a-coucher",
        "HU": "haloszoba-szett",
        "IT": "set-camera-da-letto",
        "NO": "soveromsett",
        "PL": "zestawy-do-sypialni",
        "PT": "conjuntos-de-quarto",
        "SK": "spalnova-zostava",
        "ES": "conjuntos-de-dormitorio",
        "SE": "sovrumsset"
      }
    },
    "beds-80-x-200-cm": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=3356&shop_id=1",
      categories: {
        "CZ": "postele-80-x-200",
        "DK": "senge-80-x-200-cm",
        "NL": "bedden-80x200",
        "UK": "beds-80-x-200-cm",
        "FI": "sangyt-80-x-200",
        "FR": "lit-80-x-200-cm",
        "DE": "betten-80-x-200-cm",
        "AT": "betten-80-x-200-cm",
        "CHDE": "bett-80-x-200",
        "CHFR": "lit-80-x-200-cm",
        "HU": "agyak-80-x-200-cm",
        "IT": "letti-80-x-200",
        "NO": "senger-80-x-200-cm",
        "PL": "lozka-80-x-200-cm",
        "PT": "camas-80-200",
        "SK": "postele-80-x-200",
        "ES": "camas-80-x-200-cm",
        "SE": "sangar-80-x-200"
      }
    },
    "beds-90-x-200-cm": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2528&shop_id=1",
      categories: {
        "CZ": "postele-90-x-200",
        "DK": "senge-90-x-200-cm",
        "NL": "bedden-90x200",
        "UK": "beds-90-x-200-cm",
        "FI": "sangyt-90-x-200",
        "FR": "lit-90-x-200-cm",
        "DE": "betten-90-x-200-cm",
        "AT": "betten-90-x-200-cm",
        "CHDE": "bett-90-x-200",
        "CHFR": "lit-90-x-200-cm",
        "HU": "agyak-90-x-200-cm",
        "IT": "letti-90-x-200",
        "NO": "senger-90-x-200-cm",
        "PL": "lozka-90-x-200-cm",
        "PT": "camas-90-200",
        "SK": "postele-90-x-200",
        "ES": "camas-90-x-200-cm",
        "SE": "sangar-90-x-200"
      }
    },
    "beds-140x200-cm": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2529&shop_id=1",
      categories: {
        "CZ": "postele-140-x-200",
        "DK": "senge-140-x-200-cm",
        "NL": "bedden-140x200",
        "UK": "beds-140x200-cm",
        "FI": "sangyt-140-x-200",
        "FR": "lits-140-x-200-cm",
        "DE": "betten-140-x-200-cm",
        "AT": "betten-140-x-200-cm",
        "CHDE": "bett-140-x-200",
        "CHFR": "lits-140-x-200-cm",
        "HU": "agyak-140-x-200-cm",
        "IT": "letti-140x200",
        "NO": "senger-140-x-200-cm",
        "PL": "lozka-140-x-200-cm",
        "PT": "camas-140-200",
        "SK": "postele-140-x-200",
        "ES": "camas-140-x-200-cm",
        "SE": "sang-140-x-200"
      }
    },
    "beds-160-x-200-cm": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2530&shop_id=1",
      categories: {
        "CZ": "postele-160-x-200",
        "DK": "senge-160-x-200-cm",
        "NL": "bedden-160-x-200",
        "UK": "beds-160-x-200-cm",
        "FI": "sangyt-160-x-200",
        "FR": "lits-160-x-200-cm",
        "DE": "betten-160-x-200-cm",
        "AT": "betten-160-x-200-cm",
        "CHDE": "bett-160-x-200",
        "CHFR": "lits-160-x-200-cm",
        "HU": "agyak-160-x-200-cm",
        "IT": "letti-160x200",
        "NO": "senger-160-x-200-cm",
        "PL": "lozka-160-x-200-cm",
        "PT": "camas-160-200",
        "SK": "postele-160-x-200",
        "ES": "camas-160-x-200-cm",
        "SE": "sang-160-x-200"
      }
    },
    "beds-180-x-200-cm": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2531&shop_id=1",
      categories: {
        "CZ": "postele-180-x-200",
        "DK": "senge-180-x-200-cm",
        "NL": "bedden-180-x-200",
        "UK": "beds-180-x-200-cm",
        "FI": "sangyt-180-x-200",
        "FR": "lits-180-x-200-cm",
        "DE": "betten-180-x-200-cm",
        "AT": "betten-180-x-200-cm",
        "CHDE": "bett-180-x-200",
        "CHFR": "lits-180-x-200-cm",
        "HU": "agyak-180-x-200-cm",
        "IT": "letti-180x200",
        "NO": "senger-180-x-200-cm",
        "PL": "lozka-180-x-200-cm",
        "PT": "camas-180-200",
        "SK": "postele-180-x-200",
        "ES": "camas-180-x-200-cm",
        "SE": "sang-180-x-200"
      }
    },
    "corner-sofas": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2301&shop_id=1",
      categories: {
        "CZ": "rohove-pohovky",
        "DK": "hjoernesofaer",
        "NL": "hoekbanken",
        "UK": "corner-sofas",
        "FI": "kulmasohvat",
        "FR": "canapes-d-angle",
        "DE": "ecksofas",
        "AT": "ecksofas",
        "CHDE": "ecksofas",
        "CHFR": "canapes-d-angle",
        "HU": "sarokkanapek",
        "IT": "divani-angolari",
        "NO": "hjoernesofaer",
        "PL": "sofy-narozne",
        "PT": "sofas-de-canto",
        "SK": "rohove-pohovky",
        "ES": "sofas-esquineros",
        "SE": "hornsoffor"
      }
    },
    "sofa-beds": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2307&shop_id=1",
      categories: {
        "CZ": "rozkladaci-pohovky",
        "DK": "sovesofaer",
        "NL": "slaapbanken",
        "UK": "sofa-beds",
        "FI": "vuodesohvat",
        "FR": "canapes-lits",
        "DE": "schlafsofa",
        "AT": "schlafsofa",
        "CHDE": "bettsofa",
        "CHFR": "canapes-lits",
        "HU": "kanapeagyak",
        "IT": "divani-letto",
        "NO": "sovesofaer",
        "PL": "sofa-rozkladana",
        "PT": "sofa-cama",
        "SK": "rozkladacie-pohovky",
        "ES": "sofas-cama",
        "SE": "baddsoffa"
      }
    },
    "chaise-longue": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2316&shop_id=1",
      categories: {
        "CZ": "lenosky",
        "DK": "chaiselong",
        "NL": "chaise-longues",
        "UK": "chaise-lounge",
        "FI": "divaanit",
        "FR": "chaises-longues",
        "DE": "recamiere",
        "AT": "recamiere",
        "CHDE": "recamiere",
        "CHFR": "chaises-longues",
        "HU": "rekamiek",
        "IT": "chaise-longue",
        "NO": "sjeselonger",
        "PL": "szezlong",
        "PT": "chaise-longue",
        "SK": "lenosky",
        "ES": "chaise-longues",
        "SE": "schaslonger"
      }
    },
    "fabric-sofa": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2308&shop_id=1",
      categories: {
        "CZ": "calounene-pohovky",
        "DK": "stofsofaer",
        "NL": "stoffen-banken",
        "UK": "fabric-sofa",
        "FI": "kangassohvat",
        "FR": "canapes-en-tissu",
        "DE": "polstersofa",
        "AT": "polstersofa",
        "CHDE": "polstersofa",
        "CHFR": "canapes-en-tissu",
        "HU": "karpitozott-kanapek",
        "IT": "divani-in-tessuto",
        "NO": "stoffsofaer",
        "PL": "sofa-tapicerowana",
        "PT": "sofas-de-tecido",
        "SK": "calunene-pohovky",
        "ES": "sofas-tapizados",
        "SE": "tygsoffor"
      }
    },
    "leather-sofas": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2311&shop_id=1",
      categories: {
        "CZ": "kozene-pohovky",
        "DK": "laedersofaer",
        "NL": "leren-banken",
        "UK": "leather-sofas",
        "FI": "nahkasohvat",
        "FR": "canapes-en-cuir",
        "DE": "ledersofa",
        "AT": "ledersofa",
        "CHDE": "ledersofa",
        "CHFR": "canapes-en-cuir",
        "HU": "bor-kanapek",
        "IT": "divani-in-pelle",
        "NO": "skinnsofaer",
        "PL": "sofa-skorzana",
        "PT": "sofas-em-pele",
        "SK": "kozene-pohovky",
        "ES": "sofas-de-piel",
        "SE": "skinnsoffor"
      }
    },
    "velvet-sofas": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2926&shop_id=1",
      categories: {
        "CZ": "sametove-pohovky",
        "DK": "velour-sofaer",
        "NL": "fluwelen-banken",
        "UK": "velvet-sofas",
        "FI": "samettisohvat",
        "FR": "canapes-en-velours",
        "DE": "samtsofas",
        "AT": "samtsofas",
        "CHDE": "samtsofas",
        "CHFR": "canapes-en-velours",
        "HU": "szovetbarsony-kanapek",
        "IT": "divani-in-velluto",
        "NO": "floyelssofaer",
        "PL": "sofy-welurowe",
        "PT": "sofas-de-veludo",
        "SK": "zamatove-pohovky",
        "ES": "sofas-de-terciopelo",
        "SE": "sammetssoffor"
      }
    },
    "chesterfield-sofas": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2310&shop_id=1",
      categories: {
        "CZ": "pohovky-chesterfield",
        "DK": "chesterfield-sofaer",
        "NL": "chesterfield-banken",
        "UK": "chesterfield-sofas",
        "FI": "chesterfield-sohvat",
        "FR": "canapes-chesterfield",
        "DE": "chesterfield-sofa",
        "AT": "chesterfield-sofa",
        "CHDE": "chesterfield-sofa",
        "CHFR": "canapes-chesterfield",
        "HU": "chesterfield-kanapek",
        "IT": "divani-chesterfield",
        "NO": "chesterfield-sofaer",
        "PL": "sofa-chesterfield",
        "PT": "sofas-chesterfield",
        "SK": "pohovky-chesterfield",
        "ES": "sofas-chesterfield",
        "SE": "chesterfield-soffor"
      }
    },
    "xl-sofas": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2318&shop_id=1",
      categories: {
        "CZ": "pohovky-xxl",
        "DK": "xxl-sofaer",
        "NL": "xxl-banken",
        "UK": "xl-sofas",
        "FI": "xl-sohvat",
        "FR": "canapes-taille-xl",
        "DE": "wohnlandschaft",
        "AT": "wohnlandschaft",
        "CHDE": "wohnlandschaft",
        "CHFR": "canapes-taille-xl",
        "HU": "u-alaku-ulogarniturak",
        "IT": "divani-xl",
        "NO": "xl-sofaer",
        "PL": "sofa-xxl",
        "PT": "sofas-xl",
        "SK": "pohovky-xxl",
        "ES": "sofas-xl",
        "SE": "divansoffor"
      }
    },
    "sofa-set": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2317&shop_id=1",
      categories: {
        "CZ": "dilci-sedaci-soupravy",
        "DK": "sofasaet",
        "NL": "zitgroepen",
        "UK": "sofa-set",
        "FI": "sohvaryhmat",
        "FR": "ensembles-de-salon",
        "DE": "couchgarnitur",
        "AT": "couchgarnitur",
        "CHDE": "couchgarnitur",
        "CHFR": "ensembles-de-salon",
        "HU": "ulogarnitura-szettek",
        "IT": "set-divani",
        "NO": "sofagrupper",
        "PL": "zestaw-wypoczynkowy",
        "PT": "sofas-seccionais",
        "SK": "sedacie-supravy",
        "ES": "conjuntos-de-sofas",
        "SE": "soffgrupper"
      }
    },
    "1-seater-sofas": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2302&shop_id=1",
      categories: {
        "CZ": "jednomistne-pohovky",
        "DK": "1-pers-sofaer",
        "NL": "1-zits-banken",
        "UK": "1-seater-sofas",
        "FI": "1-istuttavat-sohvat",
        "FR": "petits-canapes",
        "DE": "einzelsofas",
        "AT": "einzelsofas",
        "CHDE": "einzelsofas",
        "CHFR": "petits-canapes",
        "HU": "egyszemelyes-kanape",
        "IT": "divani-1-posto",
        "NO": "en-seters-sofaer",
        "PL": "sofy-jednoosobowe",
        "PT": "sofas-individuais",
        "SK": "jednomiestne-pohovky",
        "ES": "sofas-individuales",
        "SE": "1-sits-soffor"
      }
    },
    "2-seater-sofas": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2305&shop_id=1",
      categories: {
        "CZ": "dvoumistne-pohovky",
        "DK": "2-pers-sofaer",
        "NL": "2-zits-banken",
        "UK": "2-seater-sofas",
        "FI": "2-istuttavat-sohvat",
        "FR": "canapes-2-places",
        "DE": "2-sitzer",
        "AT": "2-sitzer",
        "CHDE": "2-sitzer",
        "CHFR": "canapes-2-places",
        "HU": "ketszemelyes-kanape",
        "IT": "divani-2-posti",
        "NO": "to-seters-sofaer",
        "PL": "sofy-dwuosobowe",
        "PT": "sofas-2-lugares",
        "SK": "dvojmiestne-pohovky",
        "ES": "sofas-2-plazas",
        "SE": "2-sits-soffor"
      }
    },
    "3-seater-sofas": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2306&shop_id=1",
      categories: {
        "CZ": "trimistne-pohovky",
        "DK": "3-pers-sofaer",
        "NL": "3-zits-banken",
        "UK": "3-seater-sofas",
        "FI": "3-istuttavat-sohvat",
        "FR": "canapes-3-places",
        "DE": "3-sitzer",
        "AT": "3-sitzer",
        "CHDE": "3-sitzer",
        "CHFR": "canapes-3-places",
        "HU": "haromszemelyes-kanape",
        "IT": "divani-3-posti",
        "NO": "tre-seters-sofaer",
        "PL": "sofy-trzyosobowe",
        "PT": "sofas-3-lugares",
        "SK": "trojmiestne-pohovky",
        "ES": "sofas-3-plazas",
        "SE": "3-sits-soffor"
      }
    },
    "kitchen-sofas": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=3111&shop_id=1",
      categories: {
        "CZ": "kuchynske-pohovky",
        "DK": "kokkensofaer",
        "NL": "eetkamerbanken",
        "UK": "kitchen-sofas",
        "FI": "keittion-sohvat",
        "FR": "banquettes-de-cuisine",
        "DE": "kuchensofas",
        "AT": "kuchensofas",
        "CHDE": "kuchensofas",
        "CHFR": "banquettes-de-cuisine",
        "HU": "eloszobai-pad",
        "IT": "divanetti",
        "NO": "spisesofaer",
        "PL": "kanapy-kuchenne",
        "PT": "sofas-de-cozinha",
        "SK": "kuchynske-pohovky",
        "ES": "sofas-de-cocina",
        "SE": "kokssoffor"
      }
    },
    "modular-sofas": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=3124&shop_id=1",
      categories: {
        "CZ": "modularni-pohovky",
        "DK": "modul-sofaer",
        "NL": "modulaire-banken",
        "UK": "modular-sofas",
        "FI": "moduulisohvat",
        "FR": "canape-modulables",
        "DE": "modulsofas",
        "AT": "modulsofas",
        "CHDE": "modulsofas",
        "CHFR": "canape-modulables",
        "HU": "kombinalhato-kanapek",
        "IT": "divani-componibili",
        "NO": "modulsofaer",
        "PL": "sofy-modulowe",
        "PT": "sofas-modulares",
        "SK": "modularne-pohovky",
        "ES": "sofas-modulares",
        "SE": "modulsoffor"
      }
    },
    "sofa-collections": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=3435&shop_id=1",
      categories: {
        "CZ": "kolekce-pohovek",
        "DK": "sofa-kollektion",
        "NL": "bank-collecties",
        "UK": "sofa-collections",
        "FI": "sohva-kokoelmat",
        "FR": "collections-de-canapes",
        "DE": "sofa-kollektionen",
        "AT": "sofa-kollektionen",
        "CHDE": "sofa-kollektionen",
        "CHFR": "collections-de-canapes",
        "HU": "kanape-kollekciok",
        "IT": "collezioni-sofa",
        "NO": "sofa-samlinger",
        "PL": "kolekcje-sof",
        "PT": "sofa-collections-pt",
        "SK": "kolekcie-pohoviek",
        "ES": "coleccion-de-sofas",
        "SE": "soffkollektioner"
      }
    },
    "garden-accessories": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2387&shop_id=1",
      categories: {
        "CZ": "zahradni-doplnky",
        "DK": "havetilbehor",
        "NL": "tuinaccessoires",
        "UK": "garden-accessories",
        "FI": "puutarhan-tarvikkeet",
        "FR": "accessoires-de-jardin",
        "DE": "gartenaccessoires",
        "AT": "gartenaccessoires",
        "CHDE": "gartenaccessoires",
        "CHFR": "accessoires-de-jardin",
        "HU": "kerti-kiegeszitok",
        "IT": "accessori-da-giardino",
        "NO": "hagetilbehoer",
        "PL": "akcesoria-ogrodowe",
        "PT": "acessorios-de-jardim",
        "SK": "zahradne-doplnky",
        "ES": "accesorios-de-jardin",
        "SE": "tradgardstillbehor"
      }
    },
    "christmas-accessories": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=3046&shop_id=1",
      categories: {
        "CZ": "vanoce",
        "DK": "jul",
        "NL": "kerst-winkel",
        "UK": "christmas-accessories",
        "FI": "joulukoristeet",
        "FR": "noel",
        "DE": "weihnachten",
        "AT": "weihnachten",
        "CHDE": "weihnachten",
        "CHFR": "noel",
        "HU": "karacsony",
        "IT": "natale",
        "NO": "jul",
        "PL": "swiateczne-akcesoria",
        "PT": "natal",
        "SK": "vianoce",
        "ES": "navidad",
        "SE": "jul"
      }
    },
    "hallway-seating": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=3375&shop_id=1",
      categories: {
        "CZ": "sezeni-do-predsine",
        "DK": "entre-siddepladser",
        "NL": "hal-zitplaatsen",
        "UK": "hallway-seating",
        "FI": "eteisen-istuimet",
        "FR": "sieges-de-couloir",
        "DE": "flursitzmoebel",
        "AT": "flursitzmoebel",
        "CHDE": "flursitzmoebel",
        "CHFR": "sieges-de-couloir",
        "HU": "eloszoba-uloalkalmatossagok",
        "IT": "sedute-ingresso-it",
        "NO": "sitteplasser-i-gangen",
        "PL": "siedziska-do-przedpokoju",
        "PT": "assentos-entrada-pt",
        "SK": "sedenie-do-predsiene",
        "ES": "asientos-entrada-es",
        "SE": "sittmobler-till-hallen"
      }
    },
    "desks-eng": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2908&shop_id=1",
      categories: {
        "CZ": "kancelarske-stoly",
        "DK": "alle-skriveborde",
        "NL": "bureaus",
        "UK": "desks-eng",
        "FI": "tyopoydat",
        "FR": "bureaux",
        "DE": "buerotische",
        "AT": "buerotische",
        "CHDE": "buerotische",
        "CHFR": "bureaux",
        "HU": "iroasztalok-hu",
        "IT": "scrivanie-it",
        "NO": "skrivebord",
        "PL": "biurka",
        "PT": "secretarias-pt",
        "SK": "pisacie-stoly-sk",
        "ES": "escritorios",
        "SE": "kontorsbord"
      }
    },
    "office-chairs": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2904&shop_id=1",
      categories: {
        "CZ": "kancelarske-zidle-a-kresla",
        "DK": "kontorstole",
        "NL": "bureaustoelen",
        "UK": "office-chairs",
        "FI": "tyotuolit",
        "FR": "sieges-de-bureau",
        "DE": "buerostuehle",
        "AT": "buerostuehle",
        "CHDE": "buerostuehle",
        "CHFR": "sieges-de-bureau",
        "HU": "irodai-szekek",
        "IT": "sedie-da-ufficio",
        "NO": "kontorstoler",
        "PL": "krzesla-biurowe",
        "PT": "cadeiras-para-secretaria",
        "SK": "kancelarske-stolicky-a-kresla",
        "ES": "sillas-para-oficina",
        "SE": "kontorsstolar"
      }
    },
    "bathroom-accessories": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2750&shop_id=1",
      categories: {
        "CZ": "koupelnove-prislusenstvi",
        "DK": "badevaerelsestilbehor",
        "NL": "badaccessoires",
        "UK": "bathroom-accessories",
        "FI": "kylpyhuoneen-tarvikkeet",
        "FR": "accessoires-salle-de-bain",
        "DE": "badaccessoires",
        "AT": "badaccessoires",
        "CHDE": "badaccessoires",
        "CHFR": "accessoires-salle-de-bain",
        "HU": "furdoszobai-kiegeszitok",
        "IT": "accessori-bagno",
        "NO": "baderomstilbehoer",
        "PL": "akcesoria-lazienkowe",
        "PT": "acessorios-para-casa-de-banho",
        "SK": "kupelnove-prislusenstvo",
        "ES": "accesorios-de-bano",
        "SE": "badrumstillbehor"
      }
    },
    "slatted-bed-bases": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2494&shop_id=1",
      categories: {
        "CZ": "rosty",
        "DK": "lamelbunde",
        "NL": "bedbodems",
        "UK": "slatted-bed-bases",
        "FI": "salepohjat",
        "FR": "sommiers-a-lattes",
        "DE": "lattenroste",
        "AT": "lattenroste",
        "CHDE": "lattenroste",
        "CHFR": "sommiers-a-lattes",
        "HU": "racsos-agyalap",
        "IT": "reti-a-doghe",
        "NO": "sengebunner",
        "PL": "stelaze",
        "PT": "estrados-de-ripas",
        "SK": "rosty",
        "ES": "somieres-de-laminas",
        "SE": "ribbottnar"
      }
    },
    "bean-bags-eng": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2413&shop_id=1",
      categories: {
        "CZ": "sedaci-vaky",
        "DK": "sekkestole",
        "NL": "zitzakken",
        "UK": "bean-bags-eng",
        "FI": "sakkituolit",
        "FR": "poufs-poire-et-coussins-de-sol",
        "DE": "sitzsack",
        "AT": "sitzsack",
        "CHDE": "sitzsack",
        "CHFR": "poufs-poire-et-coussins-de-sol",
        "HU": "babzsakok",
        "IT": "poltrone-sacco-it",
        "NO": "saccosekker",
        "PL": "fotele-worki",
        "PT": "pufes-pt",
        "SK": "sedacie-vaky",
        "ES": "pufs-cojines",
        "SE": "sittsackar"
      }
    },
    "parasols": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=2401&shop_id=1",
      categories: {
        "CZ": "slunecniky-a-rolety",
        "DK": "solbeskyttelse",
        "NL": "zonbescherming-en-accessoires",
        "UK": "parasols",
        "FI": "aurinkovarjot-ja-jalustat",
        "FR": "protections-solaires",
        "DE": "sonnenschutz",
        "AT": "sonnenschutz",
        "CHDE": "sonnenschutz",
        "CHFR": "protections-solaires",
        "HU": "kulteri-arnyekolok",
        "IT": "ombrelloni-e-parasoli-solari",
        "NO": "solskjerming",
        "PL": "parasole",
        "PT": "guarda-sois-e-acessorios",
        "SK": "slnecniky-a-tienidla",
        "ES": "sombrillas-y-toldos-vela",
        "SE": "solskydd"
      }
    },
    "new": {
      link: "https://www.prologistics.info/shop_cat.php?id=0&cat_id=1685&shop_id=1",
      categories: {
        "CZ": "novy-nabytek",
        "DK": "nyheder",
        "NL": "nieuw",
        "UK": "new",
        "FI": "uutta",
        "FR": "nouveautes",
        "DE": "neu",
        "AT": "neu",
        "CHDE": "neu",
        "CHFR": "nouveautes",
        "HU": "uj-butoraink",
        "IT": "novita",
        "NO": "nyheter",
        "PL": "nowosci",
        "PT": "novidades",
        "SK": "novy-nabytok",
        "ES": "novedades",
        "SE": "nyheter"
      }
    },
  }